version: "3.7"
services:
    inz:
        build:
            context: ./
            dockerfile: Dockerfile
        image: inz
        container_name: "inz-app"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ../:/var/www
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: serverName=server
        links:
            - db
        networks:
            - app-network
    nginx:
        image: nginx:latest
        container_name: "inz-nginx"
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www
            - ./conf/nginx:/etc/nginx/conf.d
        links:
            - inz
            - db
        networks:
            - app-network
    db:
        image: mysql:8.0.30
        container_name: "inz-db"
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: inz
            MYSQL_USER: inz
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
